/*
 * Copyright (C) The Termux Authors and Jack Palevich.
 * Licensed under the Apache License, Version 2.0.
 *
 * Modified for Herdr App: instead of spawning a local process through JNI/PTY, this session is
 * fed with remote ANSI bytes (herdr terminal frames relayed by herdr-bridge) and forwards user
 * input and size changes to a {@link RemoteIO}. The public surface used by TerminalView and
 * TerminalEmulator is kept so the upstream classes work unchanged.
 */
package com.termux.terminal;

import java.util.Arrays;
import java.util.UUID;

/**
 * A terminal session backed by a remote byte stream.
 * <p>
 * All methods must be called on the main thread.
 */
public final class TerminalSession extends TerminalOutput {

    /** Receives user input and local size changes. */
    public interface RemoteIO {
        /** Bytes typed by the user (or generated by the emulator, e.g. device reports). */
        void onWrite(byte[] data);

        /** The view's terminal grid size changed. */
        void onResize(int columns, int rows);
    }

    public final String mHandle = UUID.randomUUID().toString();

    TerminalEmulator mEmulator;

    /** Buffer to translate code points into utf8. */
    private final byte[] mUtf8InputBuffer = new byte[5];

    TerminalSessionClient mClient;

    /** Set by the application for user identification of session, not by terminal. */
    public String mSessionName;

    private final Integer mTranscriptRows;
    private final RemoteIO mRemote;
    private boolean mInputEnabled;
    private boolean mFinished;
    private int mCellWidthPixels = 1;
    private int mCellHeightPixels = 1;

    public TerminalSession(Integer transcriptRows, TerminalSessionClient client, RemoteIO remote) {
        this.mTranscriptRows = transcriptRows;
        this.mClient = client;
        this.mRemote = remote;
    }

    public void updateTerminalSessionClient(TerminalSessionClient client) {
        mClient = client;
        if (mEmulator != null) mEmulator.updateTerminalSessionClient(client);
    }

    /** When false, keystrokes and emulator replies are dropped instead of sent to the remote. */
    public void setInputEnabled(boolean enabled) {
        mInputEnabled = enabled;
    }

    public boolean isInputEnabled() {
        return mInputEnabled;
    }

    /** Called by TerminalView with the grid size that fits the view. */
    public void updateSize(int columns, int rows, int cellWidthPixels, int cellHeightPixels) {
        mCellWidthPixels = Math.max(1, cellWidthPixels);
        mCellHeightPixels = Math.max(1, cellHeightPixels);
        if (mEmulator == null) {
            initializeEmulator(columns, rows, mCellWidthPixels, mCellHeightPixels);
        } else {
            mEmulator.resize(columns, rows, mCellWidthPixels, mCellHeightPixels);
        }
        if (mRemote != null) mRemote.onResize(columns, rows);
    }

    public void initializeEmulator(int columns, int rows, int cellWidthPixels, int cellHeightPixels) {
        mEmulator = new TerminalEmulator(this, columns, rows, cellWidthPixels, cellHeightPixels, mTranscriptRows, mClient);
    }

    /**
     * Feed bytes received from the remote. {@code width}/{@code height} are the remote frame's
     * grid size; frames are cursor-addressed, so the emulator adopts that size before
     * processing them (the view clips or pads). Pass 0 to keep the current size.
     */
    public void appendRemote(byte[] data, int width, int height) {
        if (mFinished) return;
        if (mEmulator == null) {
            initializeEmulator(width > 0 ? width : 80, height > 0 ? height : 24, mCellWidthPixels, mCellHeightPixels);
        } else if (width > 0 && height > 0 && (width != mEmulator.mColumns || height != mEmulator.mRows)) {
            mEmulator.resize(width, height, mCellWidthPixels, mCellHeightPixels);
        }
        mEmulator.append(data, data.length);
        notifyScreenUpdate();
    }

    /** Write data to the remote. */
    @Override
    public void write(byte[] data, int offset, int count) {
        if (!mInputEnabled || mFinished || mRemote == null || count <= 0) return;
        mRemote.onWrite(Arrays.copyOfRange(data, offset, offset + count));
    }

    /** Write the Unicode code point to the terminal encoded in UTF-8. */
    public void writeCodePoint(boolean prependEscape, int codePoint) {
        if (codePoint > 1114111 || (codePoint >= 0xD800 && codePoint <= 0xDFFF)) {
            // 1114111 (= 2**16 + 1024**2 - 1) is the highest code point, [0xD800,0xDFFF] is the surrogate range.
            throw new IllegalArgumentException("Invalid code point: " + codePoint);
        }

        int bufferPosition = 0;
        if (prependEscape) mUtf8InputBuffer[bufferPosition++] = 27;

        if (codePoint <= /* 7 bits */0b1111111) {
            mUtf8InputBuffer[bufferPosition++] = (byte) codePoint;
        } else if (codePoint <= /* 11 bits */0b11111111111) {
            mUtf8InputBuffer[bufferPosition++] = (byte) (0b11000000 | (codePoint >> 6));
            mUtf8InputBuffer[bufferPosition++] = (byte) (0b10000000 | (codePoint & 0b111111));
        } else if (codePoint <= /* 16 bits */0b1111111111111111) {
            mUtf8InputBuffer[bufferPosition++] = (byte) (0b11100000 | (codePoint >> 12));
            mUtf8InputBuffer[bufferPosition++] = (byte) (0b10000000 | ((codePoint >> 6) & 0b111111));
            mUtf8InputBuffer[bufferPosition++] = (byte) (0b10000000 | (codePoint & 0b111111));
        } else {
            mUtf8InputBuffer[bufferPosition++] = (byte) (0b11110000 | (codePoint >> 18));
            mUtf8InputBuffer[bufferPosition++] = (byte) (0b10000000 | ((codePoint >> 12) & 0b111111));
            mUtf8InputBuffer[bufferPosition++] = (byte) (0b10000000 | ((codePoint >> 6) & 0b111111));
            mUtf8InputBuffer[bufferPosition++] = (byte) (0b10000000 | (codePoint & 0b111111));
        }
        write(mUtf8InputBuffer, 0, bufferPosition);
    }

    public TerminalEmulator getEmulator() {
        return mEmulator;
    }

    /** The terminal title as set through escape sequences or null if none set. */
    public String getTitle() {
        return (mEmulator == null) ? null : mEmulator.getTitle();
    }

    protected void notifyScreenUpdate() {
        if (mClient != null) mClient.onTextChanged(this);
    }

    /** Reset state for terminal emulator state. */
    public void reset() {
        if (mEmulator == null) return;
        mEmulator.reset();
        notifyScreenUpdate();
    }

    /** Stop accepting remote bytes and input. */
    public void finishIfRunning() {
        if (mFinished) return;
        mFinished = true;
        if (mClient != null) mClient.onSessionFinished(this);
    }

    public synchronized boolean isRunning() {
        return !mFinished;
    }

    public synchronized int getExitStatus() {
        return 0;
    }

    /** There is no local process. */
    public int getPid() {
        return -1;
    }

    /** There is no local working directory. */
    public String getCwd() {
        return null;
    }

    @Override
    public void titleChanged(String oldTitle, String newTitle) {
        if (mClient != null) mClient.onTitleChanged(this);
    }

    @Override
    public void onCopyTextToClipboard(String text) {
        if (mClient != null) mClient.onCopyTextToClipboard(this, text);
    }

    @Override
    public void onPasteTextFromClipboard() {
        if (mClient != null) mClient.onPasteTextFromClipboard(this);
    }

    @Override
    public void onBell() {
        if (mClient != null) mClient.onBell(this);
    }

    @Override
    public void onColorsChanged() {
        if (mClient != null) mClient.onColorsChanged(this);
    }
}
